---
backend: pacman
skip_if_no_internet: true
update_db: false
update_system: false
operations:
  - try_remove:
      - calamares
      - mkinitcpio-archiso
      - arch-install-scripts
      - clonezilla
      - darkhttpd
      - memtest86+
      - memtest86+-efi
      - syslinux
      - edk2-shell
      - livecd-sounds
      - grml-zsh-config
