---
dontChroot: false
timeout: 30
script:
    - command: "rm -f /etc/sudoers.d/00-oozy-live"
      timeout: 10
    - command: "rm -f /etc/sddm.conf.d/autologin.conf"
      timeout: 10
    - command: "rm -f /etc/systemd/system/oozy-live-setup.service"
      timeout: 10
    - command: "rm -f /usr/local/bin/oozy-live-setup /usr/local/bin/calamares-launch"
      timeout: 10
    - command: "rm -f /etc/hostname && echo oozy > /etc/hostname"
      timeout: 10
