---
defaultGroups:
    - name: users
      must_exist: false
      system: true
    - lp
    - video
    - network
    - storage
    - name: wheel
      must_exist: false
      system: true
    - audio
    - name: rfkill
      must_exist: false
      system: true
    - power
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: true
doReusePassword: true
passwordRequirements:
    nonempty: true
    minLength: 1
    allowWeakPasswords: true
    allowWeakPasswordsDefault: true
user:
    shell: /bin/bash
    forbidden_names: [ root, liveuser ]
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "oozy"
    forbidden_names: [ localhost, oozy-live ]
