# Oozy Linux Calamares settings
---
modules-search: [ local ]

instances:
- id:       remove-livecd
  module:   shellprocess
  config:   shellprocess-remove-livecd.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - initcpiocfg
  - initcpio
  - removeuser
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - bootloader
  - shellprocess@remove-livecd
  - umount
- show:
  - finished

branding: oozy
prompt-install: false
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
